config/routes.rb
Api::Application.routes.draw do
  resources :favorites

  resources :followings

  resources :checkins

  resources :images

  resources :rewiews

  resources :deals

  resources :establishments

  resources :locations

  resources :establishment_types

  resources :deal_types

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :users
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :user
  belongs_to :establishment
  belongs_to :deal_type
end

app/models/deal_type.rb
class DealType < ActiveRecord::Base
  has_many :deals
end

app/models/establishment.rb
class Establishment < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
  belongs_to :establishment_type
  belongs_to :checkin
  belongs_to :following
  belongs_to :favorites
  has_many :deals
  has_many :rewiews
  has_many :images
  has_and_belongs_to_many :favorites
  has_and_belongs_to_many :followings
  has_and_belongs_to_many :checkins
end

app/models/establishment_type.rb
class EstablishmentType < ActiveRecord::Base
  has_many :establishments
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/favorites.rb
class Favorites < ActiveRecord::Base
  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :users
end

app/models/following.rb
class Following < ActiveRecord::Base
  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :users
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  belongs_to :establishment
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :users
  has_many :establishments
end

app/models/rewiew.rb
class Rewiew < ActiveRecord::Base
  belongs_to :establishment
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  #->Prelang (user_login/devise)
  has_many :establishments
  has_many :rewiews
  has_many :images
  belongs_to :location
  has_and_belongs_to_many :followings
  has_and_belongs_to_many :checkins
  has_and_belongs_to_many :favorites
  has_many :deals
  has_and_belongs_to_many :users
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # The User was found in our database
    return user if user

    # The User was not found and we need to create them
    User.create(name:     auth.extra.raw_info.name,
                provider: auth.provider,
                uid:      auth.uid,
                email:    auth.info.email,
                password: Devise.friendly_token[0,20])
  end


end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deal }
      else
        format.html { render action: 'new' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:title, :title, :restrictions, :time_start, :time_end, :up_votes, :down_votes, :day, :start_date, :end_date, :user_id, :establishment_id, :deal_type_id)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @image }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :url, :tags, :user_id, :establishment_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/deal_types_helper.rb
module DealTypesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/rewiews_helper.rb
module RewiewsHelper
end

app/views/deals/_form.html.erb
<%= form_for @deal, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :restrictions, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :restrictions, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :time_start, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :time_start, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :time_end, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :time_end, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :up_votes, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :up_votes, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :down_votes, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :down_votes, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :day, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :day, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :start_date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :end_date, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  deals_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/deals/edit.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Deal %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deals/index.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => Deal %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:restrictions) %></th>
      <th><%= model_class.human_attribute_name(:time_start) %></th>
      <th><%= model_class.human_attribute_name(:time_end) %></th>
      <th><%= model_class.human_attribute_name(:up_votes) %></th>
      <th><%= model_class.human_attribute_name(:down_votes) %></th>
      <th><%= model_class.human_attribute_name(:day) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= deal.id %></td>
        <td><%= deal.title %></td>
        <td><%= deal.title %></td>
        <td><%= deal.restrictions %></td>
        <td><%= deal.time_start %></td>
        <td><%= deal.time_end %></td>
        <td><%= deal.up_votes %></td>
        <td><%= deal.down_votes %></td>
        <td><%= deal.day %></td>
        <td><%= deal.start_date %></td>
        <td><%= deal.end_date %></td>
        <td><%=l deal.created_at, format: :long %></td>
        <td>
          <%= link_to deal_path(deal), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to deal_path(deal), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_deal_path,
            :class => 'btn btn-primary' %>

app/views/deals/new.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Deal %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deals/show.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => Deal %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @deal.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @deal.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:restrictions) %></dt>
      <dd><pre class="prettyprint"><%= @deal.restrictions %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:time_start) %></dt>
      <dd><pre class="prettyprint"><%= @deal.time_start %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:time_end) %></dt>
      <dd><pre class="prettyprint"><%= @deal.time_end %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:up_votes) %></dt>
      <dd><pre class="prettyprint"><%= @deal.up_votes %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:down_votes) %></dt>
      <dd><pre class="prettyprint"><%= @deal.down_votes %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:day) %></dt>
      <dd><pre class="prettyprint"><%= @deal.day %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:start_date) %></dt>
      <dd><pre class="prettyprint"><%= @deal.start_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:end_date) %></dt>
      <dd><pre class="prettyprint"><%= @deal.end_date %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              deals_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_deal_path(@deal), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              deal_path(@deal),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>