config/routes.rb
Api::Application.routes.draw do
  resources :favorites

  resources :followings

  resources :checkins

  resources :images

  resources :rewiews

  resources :deals

  resources :establishments

  resources :locations

  resources :establishment_types

  resources :deal_types

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :users
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :user
  belongs_to :establishment
  belongs_to :deal_type
end

app/models/deal_type.rb
class DealType < ActiveRecord::Base
  has_many :deals
end

app/models/establishment.rb
class Establishment < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
  belongs_to :establishment_type
  belongs_to :checkin
  belongs_to :following
  belongs_to :favorites
  has_many :deals
  has_many :rewiews
  has_many :images
  has_and_belongs_to_many :favorites
  has_and_belongs_to_many :followings
  has_and_belongs_to_many :checkins
end

app/models/establishment_type.rb
class EstablishmentType < ActiveRecord::Base
  has_many :establishments
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/favorites.rb
class Favorites < ActiveRecord::Base
  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :users
end

app/models/following.rb
class Following < ActiveRecord::Base
  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :users
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  belongs_to :establishment
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :users
  has_many :establishments
end

app/models/rewiew.rb
class Rewiew < ActiveRecord::Base
  belongs_to :establishment
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  #->Prelang (user_login/devise)
  has_many :establishments
  has_many :rewiews
  has_many :images
  belongs_to :location
  has_and_belongs_to_many :followings
  has_and_belongs_to_many :checkins
  has_and_belongs_to_many :favorites
  has_many :deals
  has_and_belongs_to_many :users
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # The User was found in our database
    return user if user

    # The User was not found and we need to create them
    User.create(name:     auth.extra.raw_info.name,
                provider: auth.provider,
                uid:      auth.uid,
                email:    auth.info.email,
                password: Devise.friendly_token[0,20])
  end


end

app/controllers/deal_types_controller.rb
class DealTypesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_deal_type, only: [:show, :edit, :update, :destroy]

  # GET /deal_types
  # GET /deal_types.json
  def index
    @deal_types = DealType.all
  end

  # GET /deal_types/1
  # GET /deal_types/1.json
  def show
  end

  # GET /deal_types/new
  def new
    @deal_type = DealType.new
  end

  # GET /deal_types/1/edit
  def edit
  end

  # POST /deal_types
  # POST /deal_types.json
  def create
    @deal_type = DealType.new(deal_type_params)

    respond_to do |format|
      if @deal_type.save
        format.html { redirect_to @deal_type, notice: 'Deal type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deal_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @deal_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deal_types/1
  # PATCH/PUT /deal_types/1.json
  def update
    respond_to do |format|
      if @deal_type.update(deal_type_params)
        format.html { redirect_to @deal_type, notice: 'Deal type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deal_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deal_types/1
  # DELETE /deal_types/1.json
  def destroy
    @deal_type.destroy
    respond_to do |format|
      format.html { redirect_to deal_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal_type
      @deal_type = DealType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_type_params
      params.require(:deal_type).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/deal_types_helper.rb
module DealTypesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/rewiews_helper.rb
module RewiewsHelper
end

app/views/deal_types/_form.html.erb
<%= form_for @deal_type, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  deal_types_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/deal_types/edit.html.erb
<%- model_class = DealType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => DealType %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deal_types/index.html.erb
<%- model_class = DealType -%>
<div class="page-header">
  <h1><%=t '.title', :default => DealType %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @deal_types.each do |deal_type| %>
      <tr>
        <td><%= deal_type.id %></td>
        <td><%= deal_type.name %></td>
        <td><%= deal_type.description %></td>
        <td><%=l deal_type.created_at, format: :long %></td>
        <td>
          <%= link_to deal_type_path(deal_type), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to deal_type_path(deal_type), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_deal_type_path,
            :class => 'btn btn-primary' %>

app/views/deal_types/new.html.erb
<%- model_class = DealType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => DealType %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deal_types/show.html.erb
<%- model_class = DealType -%>
<div class="page-header">
  <h1><%=t '.title', :default => DealType %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @deal_type.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @deal_type.description %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              deal_types_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_deal_type_path(@deal_type), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              deal_type_path(@deal_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>