config/routes.rb
Api::Application.routes.draw do
  resources :favorites

  resources :followings

  resources :checkins

  resources :images

  resources :rewiews

  resources :deals

  resources :establishments

  resources :locations

  resources :establishment_types

  resources :deal_types

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :users
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :user
  belongs_to :establishment
  belongs_to :deal_type
end

app/models/deal_type.rb
class DealType < ActiveRecord::Base
  has_many :deals
end

app/models/establishment.rb
class Establishment < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
  belongs_to :establishment_type
  belongs_to :checkin
  belongs_to :following
  belongs_to :favorites
  has_many :deals
  has_many :rewiews
  has_many :images
  has_and_belongs_to_many :favorites
  has_and_belongs_to_many :followings
  has_and_belongs_to_many :checkins
end

app/models/establishment_type.rb
class EstablishmentType < ActiveRecord::Base
  has_many :establishments
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/favorites.rb
class Favorites < ActiveRecord::Base
  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :users
end

app/models/following.rb
class Following < ActiveRecord::Base
  has_and_belongs_to_many :establishments
  has_and_belongs_to_many :users
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  belongs_to :establishment
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :users
  has_many :establishments
end

app/models/rewiew.rb
class Rewiew < ActiveRecord::Base
  belongs_to :establishment
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  #->Prelang (user_login/devise)
  has_many :establishments
  has_many :rewiews
  has_many :images
  belongs_to :location
  has_and_belongs_to_many :followings
  has_and_belongs_to_many :checkins
  has_and_belongs_to_many :favorites
  has_many :deals
  has_and_belongs_to_many :users
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # The User was found in our database
    return user if user

    # The User was not found and we need to create them
    User.create(name:     auth.extra.raw_info.name,
                provider: auth.provider,
                uid:      auth.uid,
                email:    auth.info.email,
                password: Devise.friendly_token[0,20])
  end


end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deal }
      else
        format.html { render action: 'new' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:title, :title, :restrictions, :time_start, :time_end, :up_votes, :down_votes, :day, :start_date, :end_date, :user_id, :establishment_id, :deal_type_id)
    end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_establishment, only: [:show, :edit, :update, :destroy]

  # GET /establishments
  # GET /establishments.json
  def index
    @establishments = Establishment.all
  end

  # GET /establishments/1
  # GET /establishments/1.json
  def show
  end

  # GET /establishments/new
  def new
    @establishment = Establishment.new
  end

  # GET /establishments/1/edit
  def edit
  end

  # POST /establishments
  # POST /establishments.json
  def create
    @establishment = Establishment.new(establishment_params)

    respond_to do |format|
      if @establishment.save
        format.html { redirect_to @establishment, notice: 'Establishment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @establishment }
      else
        format.html { render action: 'new' }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /establishments/1
  # PATCH/PUT /establishments/1.json
  def update
    respond_to do |format|
      if @establishment.update(establishment_params)
        format.html { redirect_to @establishment, notice: 'Establishment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /establishments/1
  # DELETE /establishments/1.json
  def destroy
    @establishment.destroy
    respond_to do |format|
      format.html { redirect_to establishments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_establishment
      @establishment = Establishment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def establishment_params
      params.require(:establishment).permit(:name, :description, :rating, :address, :city, :state, :zip, :neighborhoods, :hours, :price, :phone, :bar, :facebook, :menu, :user_id, :location_id, :establishment_type_id, :checkin_id, :following_id, :favorites_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/deal_types_helper.rb
module DealTypesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/rewiews_helper.rb
module RewiewsHelper
end

app/views/establishments/_form.html.erb
<%= form_for @establishment, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rating, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :rating, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :city, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :state, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zip, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :zip, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :neighborhoods, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :neighborhoods, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :hours, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :hours, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :price, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :phone, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bar, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :bar, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :facebook, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :facebook, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :menu, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :menu, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  establishments_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/establishments/edit.html.erb
<%- model_class = Establishment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Establishment %></h1>
</div>
<%= render :partial => 'form' %>

app/views/establishments/index.html.erb
<%- model_class = Establishment -%>
<div class="page-header">
  <h1><%=t '.title', :default => Establishment %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:zip) %></th>
      <th><%= model_class.human_attribute_name(:neighborhoods) %></th>
      <th><%= model_class.human_attribute_name(:hours) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:bar) %></th>
      <th><%= model_class.human_attribute_name(:facebook) %></th>
      <th><%= model_class.human_attribute_name(:menu) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @establishments.each do |establishment| %>
      <tr>
        <td><%= establishment.id %></td>
        <td><%= establishment.name %></td>
        <td><%= establishment.description %></td>
        <td><%= establishment.rating %></td>
        <td><%= establishment.address %></td>
        <td><%= establishment.city %></td>
        <td><%= establishment.state %></td>
        <td><%= establishment.zip %></td>
        <td><%= establishment.neighborhoods %></td>
        <td><%= establishment.hours %></td>
        <td><%= establishment.price %></td>
        <td><%= establishment.phone %></td>
        <td><%= establishment.bar %></td>
        <td><%= establishment.facebook %></td>
        <td><%= establishment.menu %></td>
        <td><%=l establishment.created_at, format: :long %></td>
        <td>
          <%= link_to establishment_path(establishment), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to establishment_path(establishment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_establishment_path,
            :class => 'btn btn-primary' %>

app/views/establishments/new.html.erb
<%- model_class = Establishment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Establishment %></h1>
</div>
<%= render :partial => 'form' %>

app/views/establishments/show.html.erb
<%- model_class = Establishment -%>
<div class="page-header">
  <h1><%=t '.title', :default => Establishment %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:rating) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.rating %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.address %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:city) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.city %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:state) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.state %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:zip) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.zip %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:neighborhoods) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.neighborhoods %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:hours) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.hours %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:price) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.price %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.phone %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:bar) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.bar %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:facebook) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.facebook %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:menu) %></dt>
      <dd><pre class="prettyprint"><%= @establishment.menu %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              establishments_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_establishment_path(@establishment), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              establishment_path(@establishment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>